apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-aula01-dev
resources:
  - ../../base
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kube-news
      spec:
        replicas: 1
